# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:

  # Datastore configuration
  datastore:
    # Name of a deployed Datastore to use.
    name: inmemory


  containers:
     - image: lightbend-docker-registry.bintray.io/cloudstate-samples/shopping-cart-js:latest

