# This file comes from https://raw.githubusercontent.com/cloudstateio/cloudstate/v0.5.1/samples/js-shopping-cart/cassandra-store.yaml
# Deployment spec for a store. A store is a logical abstraction over a database
# deployment, and captures how to deploy and connect to that database. Multiple
# StatefulServices's would use a single store.
apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: cassandra
spec:

  # The type of store - valid values would come from an enum of supported databases.
  type: Cassandra

  # The deployment type, ie, how this store is deployed. Valid values would depend on
  # the store type, but all types would support "Unmanaged", which indicates that the
  # operator doesn't manage/deploy the database itself, ie, the user has to deploy
  # the database themselves. For Cassandra, future supported values might include
  # "GoogleCloudMarketplace", which would deploy Cassandra using Google's Application
  # CRD, or "InstaclustrOperator", which would deploy Cassandra using Instaclustr's
  # Cassandra operator.
  deployment: Unmanaged

  # Type and deployment specific configuration for the store.
  config:

    # The name of the unmanaged Cassandra service to connect to.
    # Based on  https://gitter.im/CloudState-IO/community?at=5e219916ea55e3623e6ccc41, the format should be 
    #  <service-name>.<namespace-name>.svc.cluster.local
    service: cassandra-cassandra-svc.cloudstate.svc.cluster.local
